// Generated by Selenium IDE

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class TestFindVacancyTestAutomationEngineerTest {

    private WebDriver driver;

    private Map<String, Object> vars;

    JavascriptExecutor js;

    private final By NAVIGATION_BAR = By.id("navbarCollapse");

    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "C:\\srdev\\geckodriver.exe");
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testFindVacancyTestAutomationEngineer() {
        driver.get("https://ctco.lv/");
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(NAVIGATION_BAR));
        }
        assertThat(driver.getTitle(), is("C.T.Co People"));
        driver.manage().window().setSize(new Dimension(1936, 1056));
        new CTCoPage(driver).openVacancies()
                .clickOnVacancy("Test Automation Engineer");

        {
            List<WebElement> elements = driver.findElements(By.xpath("//p[contains(.,\'Professional skills and qualification:\')" +
                    "]/following-sibling::p[contains(.,\'REST Assured\')]"));
            assert (elements.size() > 0);
        }
        {
            List<WebElement> elements = driver.findElements(By.xpath("//p[contains(.,\'Professional skills and qualification:\')" +
                    "]/following-sibling::p[contains(.,\'Good level in English reading /speaking /writing\')]"));
            assert (elements.size() > 0);
        }
        {
            List<WebElement> elements = driver.findElements(By.xpath("//p[contains(.,\'Professional skills and qualification:\')" +
                    "]/following-sibling::p[contains(.,\' communication skills\')]"));
            assert (elements.size() > 0);
        }
    }
}
