// Generated by Selenium IDE

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

public class TestFindTeaPotAndAddToCart {

    private WebDriver driver;

    private Map<String, Object> vars;

    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "C:\\srdev\\geckodriver.exe");
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testBuyTeaSpot() {
        driver.get("https://www.1a.lv/");
        driver.manage().window().setSize(new Dimension(1666, 965));
        {
            WebElement element = driver.findElement(By.cssSelector(".items"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        assertThat(driver.findElement(By.cssSelector(".items")).getText(), is("0"));
        {
            WebElement element = driver.findElement(By.id("shopping_cart_container"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }

        driver.findElement(By.id("search_products_text_field")).click();
        driver.findElement(By.id("search_products_text_field")).sendKeys("tea pot");
        driver.findElement(By.id("search_products_text_field")).sendKeys(Keys.ENTER);
        js.executeScript("window.scrollTo(0,0)");
        driver.findElement(By.cssSelector(".ait-search-results")).click();
        driver.findElement(By.cssSelector(".ait-search-result-count > span")).click();
        assertThat(driver.findElement(By.cssSelector(".ait-search-result-count > span")).getText(), is("13"));
        driver.findElement(By.cssSelector("#search-category-image-grid > .ait-search-result-image-box:nth-child(2) .ait-search-result-image"))
                .click();
        js.executeScript("window.scrollTo(0,0)");
        driver.findElement(By.cssSelector(".ait-search-result-count > span")).click();
        assertThat(driver.findElement(By.cssSelector(".ait-search-result-count > span")).getText(), is("2"));
        assertThat(driver.findElement(By.cssSelector(".same-height-left .button > span")).getText(), is("IELIKT GROZĀ"));
        driver.findElement(By.cssSelector(".same-height-left .button > span")).click();
        assertThat(driver.findElement(By.cssSelector(".product-is-in-cart > span")).getText(), is("UZ GROZU"));
        {
            WebElement element = driver.findElement(By.cssSelector(".title-link > .items"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        assertThat(driver.findElement(By.cssSelector(".title-link > .items")).getText(), is("1"));
        {
            WebElement element = driver.findElement(By.cssSelector(".title-link > .items"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".title-link > .items")).click();
        assertThat(driver.findElement(By.linkText("Iztīrīt pirkumu grozu")).getText(), is("Iztīrīt pirkumu grozu"));
        driver.findElement(By.linkText("Iztīrīt pirkumu grozu")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".items"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        assertThat(driver.findElement(By.cssSelector(".items")).getText(), is("0"));
        WebElement element = driver.findElement(By.id("shopping_cart_container"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).perform();
        assertThat(driver.findElement(By.cssSelector(".cartdrop > .empty")).getText(), is("Pirkumu grozā nav nevienas preces"));
    }

}
